# NUMPY

In [3]:
import numpy as np

## Numpy Arrays

In [4]:
my_list = [1,2,3,4,5]

In [7]:
my_array = np.array(my_list)
print(my_list,type(my_list))
print(my_array,type(my_array))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [20]:
my_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Some of Examples of Numpy Functions

In [10]:
print(np.arange(0,10,2))
print(np.arange(0,11,2))

[0 2 4 6 8]
[ 0  2  4  6  8 10]


In [11]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.random.randint(-10,11, (3,3))

array([[  0,   0, -10],
       [ -2,  -3,  -7],
       [ -5,   6,  -8]])

In [14]:
np.random.seed(101) # Only effects this cell

np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [15]:
np.random.randint(0,100,10)

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [17]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
print(arr)
print("Min: ",arr.min())
print("Max: ",arr.max())

[95 11 81 70 63 87 75  9 77 40]
Min:  9
Max:  95


# pandas

The package pandas contains two powerful objects, series and DataFrames, which allows for the easy reference to collections of and manipulations of diverse datasets.  

## Dataframes

# Seaborn